//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class COLMENAS : XPBaseObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        DateTime fFechaRevision;
        public DateTime FechaRevision
        {
            get { return fFechaRevision; }
            set { SetPropertyValue<DateTime>(nameof(FechaRevision), ref fFechaRevision, value); }
        }
        decimal fAlto;
        [DbType("decimal(4,2)")]
        public decimal Alto
        {
            get { return fAlto; }
            set { SetPropertyValue<decimal>(nameof(Alto), ref fAlto, value); }
        }
        decimal fAncho;
        [DbType("decimal(4,2)")]
        public decimal Ancho
        {
            get { return fAncho; }
            set { SetPropertyValue<decimal>(nameof(Ancho), ref fAncho, value); }
        }
        string fEstado;
        public string Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<string>(nameof(Estado), ref fEstado, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        bool fEstaCatada;
        [ColumnDefaultValue(false)]
        public bool EstaCatada
        {
            get { return fEstaCatada; }
            set { SetPropertyValue<bool>(nameof(EstaCatada), ref fEstaCatada, value); }
        }
        bool fTieneCria;
        [ColumnDefaultValue(false)]
        public bool TieneCria
        {
            get { return fTieneCria; }
            set { SetPropertyValue<bool>(nameof(TieneCria), ref fTieneCria, value); }
        }
        [Association(@"CUADROSReferencesCOLMENAS")]
        public XPCollection<CUADROS> CUADROSCollection { get { return GetCollection<CUADROS>(nameof(CUADROSCollection)); } }
        [Association(@"ALZASReferencesCOLMENAS")]
        public XPCollection<ALZAS> ALZASCollection { get { return GetCollection<ALZAS>(nameof(ALZASCollection)); } }
    }

}
