//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class CONFIGURACION : XPBaseObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        USUARIOS fUsuario;
        [Association(@"CONFIGURACIONReferencesUSUARIOS")]
        public USUARIOS Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<USUARIOS>(nameof(Usuario), ref fUsuario, value); }
        }
        bool fUtilizaIVA;
        [ColumnDefaultValue(false)]
        public bool UtilizaIVA
        {
            get { return fUtilizaIVA; }
            set { SetPropertyValue<bool>(nameof(UtilizaIVA), ref fUtilizaIVA, value); }
        }
    }

}
