//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class COSECHAS : XPBaseObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        DateTime fFechaCosecha;
        public DateTime FechaCosecha
        {
            get { return fFechaCosecha; }
            set { SetPropertyValue<DateTime>(nameof(FechaCosecha), ref fFechaCosecha, value); }
        }
        DateTime fFechaVendidoTodo;
        public DateTime FechaVendidoTodo
        {
            get { return fFechaVendidoTodo; }
            set { SetPropertyValue<DateTime>(nameof(FechaVendidoTodo), ref fFechaVendidoTodo, value); }
        }
        decimal fCantidadSacada;
        [DbType("decimal(10,4)")]
        public decimal CantidadSacada
        {
            get { return fCantidadSacada; }
            set { SetPropertyValue<decimal>(nameof(CantidadSacada), ref fCantidadSacada, value); }
        }
        [Association(@"MIELReferencesCOSECHAS")]
        public XPCollection<MIEL> MIELs { get { return GetCollection<MIEL>(nameof(MIELs)); } }
    }

}
