//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class LINEAS_COMPRAS : XPBaseObject
    {
        public struct CompositeField1Struct
        {
            [Persistent("Id")]
            public long Id { get; set; }
            [Association(@"LINEAS_COMPRASReferencesCOMPRAS")]
            [Persistent("Cabecera")]
            public COMPRAS Cabecera { get; set; }
        }
        [Key, Persistent]
        public CompositeField1Struct CompositeField1;
        MATERIALES fMaterial;
        [Association(@"LINEAS_COMPRASReferencesMATERIALES")]
        public MATERIALES Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<MATERIALES>(nameof(Material), ref fMaterial, value); }
        }
        decimal fDto;
        [DbType("decimal(5,2)")]
        public decimal Dto
        {
            get { return fDto; }
            set { SetPropertyValue<decimal>(nameof(Dto), ref fDto, value); }
        }
        decimal fCantidad;
        [DbType("decimal(8,2)")]
        public decimal Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<decimal>(nameof(Cantidad), ref fCantidad, value); }
        }
        string fUnidadMedida;
        [Size(5)]
        public string UnidadMedida
        {
            get { return fUnidadMedida; }
            set { SetPropertyValue<string>(nameof(UnidadMedida), ref fUnidadMedida, value); }
        }
        IMPUESTOS fImpuesto;
        [Association(@"LINEAS_COMPRASReferencesIMPUESTOS")]
        public IMPUESTOS Impuesto
        {
            get { return fImpuesto; }
            set { SetPropertyValue<IMPUESTOS>(nameof(Impuesto), ref fImpuesto, value); }
        }
        decimal fTotalBruto;
        [DbType("decimal(10,4)")]
        public decimal TotalBruto
        {
            get { return fTotalBruto; }
            set { SetPropertyValue<decimal>(nameof(TotalBruto), ref fTotalBruto, value); }
        }
        decimal fTotalNeto;
        [DbType("decimal(10,4)")]
        public decimal TotalNeto
        {
            get { return fTotalNeto; }
            set { SetPropertyValue<decimal>(nameof(TotalNeto), ref fTotalNeto, value); }
        }
        decimal fTotalDtos;
        [DbType("decimal(10,4)")]
        public decimal TotalDtos
        {
            get { return fTotalDtos; }
            set { SetPropertyValue<decimal>(nameof(TotalDtos), ref fTotalDtos, value); }
        }
        decimal fTotalImpuestos;
        [DbType("decimal(10,4)")]
        public decimal TotalImpuestos
        {
            get { return fTotalImpuestos; }
            set { SetPropertyValue<decimal>(nameof(TotalImpuestos), ref fTotalImpuestos, value); }
        }
    }

}
