//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class VENTAS : XPBaseObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>(nameof(Id), ref fId, value); }
        }
        CLIENTES fCliente;
        [Association(@"VENTASReferencesCLIENTES")]
        public CLIENTES Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<CLIENTES>(nameof(Cliente), ref fCliente, value); }
        }
        string fFechaVenta;
        public string FechaVenta
        {
            get { return fFechaVenta; }
            set { SetPropertyValue<string>(nameof(FechaVenta), ref fFechaVenta, value); }
        }
        decimal fTotalBruto;
        [DbType("decimal(10,4)")]
        public decimal TotalBruto
        {
            get { return fTotalBruto; }
            set { SetPropertyValue<decimal>(nameof(TotalBruto), ref fTotalBruto, value); }
        }
        decimal fTotalDtos;
        [DbType("decimal(10,4)")]
        public decimal TotalDtos
        {
            get { return fTotalDtos; }
            set { SetPropertyValue<decimal>(nameof(TotalDtos), ref fTotalDtos, value); }
        }
        decimal fTotalImpuestos;
        [DbType("decimal(10,4)")]
        public decimal TotalImpuestos
        {
            get { return fTotalImpuestos; }
            set { SetPropertyValue<decimal>(nameof(TotalImpuestos), ref fTotalImpuestos, value); }
        }
        decimal fTotalNeto;
        [DbType("decimal(10,4)")]
        public decimal TotalNeto
        {
            get { return fTotalNeto; }
            set { SetPropertyValue<decimal>(nameof(TotalNeto), ref fTotalNeto, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        [Association(@"LINEAS_VENTASReferencesVENTAS")]
        public XPCollection<LINEAS_VENTAS> LINEAS_VENTASs { get { return GetCollection<LINEAS_VENTAS>(nameof(LINEAS_VENTASs)); } }
    }

}
