//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gestor_Productos.Database.ORM_GestProc
{

    public partial class VENTAS : XPBaseObject
    {
        long fField1;
        [Key(true)]
        public long Field1
        {
            get { return fField1; }
            set { SetPropertyValue<long>(nameof(Field1), ref fField1, value); }
        }
    }

}
